name: Intraday-Telegram-Alert

on:
  # Allows you to manually trigger a run from the Actions tab
  workflow_dispatch: []

  # Also runs automatically on weekdays at 09:30 IST (04:00 UTC)
  schedule:
    - cron: '0 4 * * 1-5'

jobs:
  send_intraday_picks:
    name: Compute and Send Intraday Picks
    runs-on: ubuntu-latest

    steps:
      # 1) Check out repository
      - uses: actions/checkout@v3

      # 2) Set up Python 3.10
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3) Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas nsepython requests

      # 4) Run the intraday-picks script, passing in Telegram secrets
      - name: Run Intraday Picks Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python nse_intraday_picks.py
