name: Intraday-Telegram-Alert

on:
  workflow_dispatch: []     # ← allows manual runs
  schedule:
    - cron: '0 4 * * 1-5'   # ← 04:00 UTC Mon–Fri → 09:30 IST

jobs:
  send_intraday_picks:
    name: Compute and Send Intraday Picks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas nsepython requests

      - name: Run Intraday Picks Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python nse_intraday_picks.py
